server:
  port: 8888
spring:
  application:
    name: e-commerce-config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mahongsheng/e-commerce-config.git #配置文件所在仓库
          default-label: main #配置文件分支
          search-paths: config #配置文件所在根目录
          username: mahhss@foxmail.com
          password: mage@1125