server:
  port: 8888

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://8.130.29.183:8761/eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: e-commerce-config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ma_hongsheng/e-commerce-config.git #配置文件所在仓库
          default-label: master #配置文件分支
          search-paths: config #配置文件所在根目录
          username: xxx
          password: xxx