server:
  port: 9010

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: e-commerce-admin
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      label: main
      profile: dev