server:
  port: 9010

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: e-commerce-admin
  datasource:
    url: jdbc:mysql://106.13.127.90:3306/e_commerce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: work
    password: mydatabase
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 101.201.254.128 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
      label: main
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://8.130.29.183:8761//eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath*:mapper/*.xml

value:
  zuul-uri: "http://localhost:9000"

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /autoShow
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /log/generateValidateCode

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: e-commerce-admin #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头